template: _templates/hero.html

pages:
- index: 
    generate: index.html
    resource: _resources/home.yml
    views : 
        intro: _views/home-intro.erb
        main: _views/home-main.erb
- import: 
    generate: import.html
    resource: _resources/import.yml
    views : 
        intro: _views/import-intro.erb
        main: _views/import-main.erb
- edit: 
    generate: edit.html
    resource: _resources/edit.yml
    views : 
        intro: _views/edit-intro.erb
        main: _views/edit-main.erb
- publish: 
    generate: publish.html
    resource: _resources/publish.yml
    views : 
        intro: _views/publish-intro.erb
        main: _views/publish-main.erb
        
bundles:
- base:
    generate: scripts/base-v1.0.js
    files:
     - scripts/demo.js
- libraries-min:
    generate: scripts/libraries-min-v1.1.js
    files:
     - scripts/bootstrap.js
- base:
    generate: stylesheets/base-v1.1.css
    files:
      - stylesheets/bootstrap.css
      - stylesheets/demo.css
      - stylesheets/bootstrap-responsive.css

